In [1]:
import pandas as pd

In [2]:
csv2017 = "Resources/201712-citibike-tripdata.csv"
csv2018 = "Resources/201812-citibike-tripdata.csv"
csv2019 = "Resources/201912-citibike-tripdata.csv"
csv2020 = "Resources/202012-citibike-tripdata.csv"
csv2021 = "Resources/202112-citibike-tripdata.csv"
csv2022 = "Resources/202209-citibike-tripdata.csv"

df_2017 = pd.read_csv(csv2017)
df_2018 = pd.read_csv(csv2018)
df_2019 = pd.read_csv(csv2019)
df_2020 = pd.read_csv(csv2020)
df_2021 = pd.read_csv(csv2021)
df_2022 = pd.read_csv(csv2022)

/var/folders/sp/6plkjdmn5qsb1910x_z26fnm0000gn/T/ipykernel_590/2743592218.py:12: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv(csv2021)
/var/folders/sp/6plkjdmn5qsb1910x_z26fnm0000gn/T/ipykernel_590/2743592218.py:13: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv(csv2022)

In [3]:
df_2017["usertype"] = df_2017["usertype"].replace("Subscriber","member")
df_2017["usertype"] = df_2017["usertype"].replace("Customer","casual")
df_2017["year"]="2017"
df_2018["usertype"] = df_2018["usertype"].replace("Subscriber","member")
df_2018["usertype"] = df_2018["usertype"].replace("Customer","casual")
df_2018["year"]="2018"
df_2019["usertype"] = df_2019["usertype"].replace("Subscriber","member")
df_2019["usertype"] = df_2019["usertype"].replace("Customer","casual")
df_2019["year"]="2019"
df_2020["usertype"] = df_2020["usertype"].replace("Subscriber","member")
df_2020["usertype"] = df_2020["usertype"].replace("Customer","casual")
df_2020["year"]="2020"

In [4]:
df_2017 = df_2017.drop("gender", axis=1)
df_2017 = df_2017.drop("birth year", axis=1)
df_2018 = df_2018.drop("gender", axis=1)
df_2018 = df_2018.drop("birth year", axis=1)
df_2019 = df_2019.drop("gender", axis=1)
df_2019 = df_2019.drop("birth year", axis=1)
df_2020 = df_2020.drop("gender", axis=1)
df_2020 = df_2020.drop("birth year", axis=1)

In [5]:
df_2017 = df_2017.rename(columns={"bikeid": "ride_id", "starttime":"started_at","stoptime": "ended_at", "start station id": "start_station_id", "start station name": "start_station_name", "start station latitude":"start_lat", "start station longitude": "start_lng", "end station id": "end_station_id", "end station name": "end_station_name", "end station latitude":"end_lat", "end station longitude": "end_lng", "usertype":"member_casual"})
df_2018 = df_2018.rename(columns={"bikeid": "ride_id", "starttime":"started_at","stoptime": "ended_at", "start station id": "start_station_id", "start station name": "start_station_name", "start station latitude":"start_lat", "start station longitude": "start_lng", "end station id": "end_station_id", "end station name": "end_station_name", "end station latitude":"end_lat", "end station longitude": "end_lng", "usertype":"member_casual"})
df_2019 = df_2019.rename(columns={"bikeid": "ride_id", "starttime":"started_at","stoptime": "ended_at", "start station id": "start_station_id", "start station name": "start_station_name", "start station latitude":"start_lat", "start station longitude": "start_lng", "end station id": "end_station_id", "end station name": "end_station_name", "end station latitude":"end_lat", "end station longitude": "end_lng", "usertype":"member_casual"})
df_2020 = df_2020.rename(columns={"bikeid": "ride_id", "starttime":"started_at","stoptime": "ended_at", "start station id": "start_station_id", "start station name": "start_station_name", "start station latitude":"start_lat", "start station longitude": "start_lng", "end station id": "end_station_id", "end station name": "end_station_name", "end station latitude":"end_lat", "end station longitude": "end_lng", "usertype":"member_casual"})

In [6]:
df_2021=df_2021.drop("rideable_type",axis=1)
df_2022=df_2022.drop("rideable_type",axis=1)
df_2021["year"]="2021"
df_2022["year"]="2022"

In [7]:
df_2017_2022 = pd.concat([df_2017, df_2018, df_2019, df_2020, df_2021, df_2022], ignore_index=True)

In [8]:
df_2017_2022["City"] = "New York City"

In [12]:
df_2017_2022["start_station_name"].value_counts()

W 21 St & 6 Ave                   49198
E 17 St & Broadway                42918
Broadway & E 14 St                37711
6 Ave & W 33 St                   37410
8 Ave & W 31 St                   36348
                                  ...
Clinton St & Newark St                3
Lab - NYC                             2
Monroe St & Marcus Garvey Blvd        2
23 Rd & 29 St                         1
Handlebar @ Gowanus                   1
Name: start_station_name, Length: 1797, dtype: int64

In [13]:
df_2017_2022["end_station_name"].value_counts()

W 21 St & 6 Ave                             49549
E 17 St & Broadway                          44772
Broadway & E 14 St                          38208
6 Ave & W 33 St                             37302
University Pl & E 14 St                     37129
                                            ...
Dixon Mills                                     1
Glenwood Ave                                    1
Hoboken Terminal - Hudson St & Hudson Pl        1
Lincoln Park                                    1
Columbus Dr at Exchange Pl                      1
Name: end_station_name, Length: 1852, dtype: int64

In [17]:
df1=df_2017_2022.groupby("start_station_name").filter(lambda x: len(x) > 25000)
df1

,tripduration,started_at,ended_at,start_station_id,start_station_name,start_lat,start_lng,end_station_id,end_station_name,end_lat,end_lng,ride_id,member_casual,year,City
15,552.0,2017-12-01 00:01:20,2017-12-01 00:10:33,379,W 31 St & 7 Ave,40.749156,-73.991600,382,University Pl & E 14 St,40.734927,-73.992005,21432,member,2017,New York City
17,2239.0,2017-12-01 00:01:38,2017-12-01 00:38:58,486,Broadway & W 29 St,40.746201,-73.988557,540,Lexington Ave & E 29 St,40.743116,-73.982154,32543,member,2017,New York City
25,917.0,2017-12-01 00:03:04,2017-12-01 00:18:22,479,9 Ave & W 45 St,40.760193,-73.991255,435,W 21 St & 6 Ave,40.741740,-73.994156,31477,member,2017,New York City
35,1718.0,2017-12-01 00:04:07,2017-12-01 00:32:45,168,W 18 St & 6 Ave,40.739713,-73.994564,467,Dean St & 4 Ave,40.683125,-73.978951,17293,member,2017,New York City
38,712.0,2017-12-01 00:04:19,2017-12-01 00:16:12,358,Christopher St & Greenwich St,40.732916,-74.007114,474,5 Ave & E 29 St,40.745168,-73.986831,24973,member,2017,New York City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9205913,NaN,2022-09-13 16:39:51,2022-09-13 16:48:54,6173.08,Broadway & W 25 St,40.742869,-73.989186,5788.13,Lafayette St & E 8 St,40.730207,-73.991026,E06DBDF7AE400007,member,2022,New York City
9205924,NaN,2022-09-07 19:24:22,2022-09-07 19:37:14,6173.08,Broadway & W 25 St,40.742869,-73.989186,5626.15,1 Ave & E 6 St,40.726331,-73.986169,B769D03F13B281AE,member,2022,New York City
9206004,NaN,2022-09-30 14:06:40,2022-09-30 14:25:19,7175.05,Columbus Ave & W 72 St,40.777244,-73.978896,8123.02,Broadway & W 155 St,40.832990,-73.945920,EEF2E04D20191661,member,2022,New York City
9206010,NaN,2022-09-27 13:07:03,2022-09-27 13:28:03,7175.05,Columbus Ave & W 72 St,40.777057,-73.978985,6389.09,E 39 St & Lexington Ave,40.749499,-73.977292,9905EDB31405A583,member,2022,New York City
9206013,NaN,2022-09-22 16:38:43,2022-09-22 17:42:42,7175.05,Columbus Ave & W 72 St,40.776888,-73.979145,4348.07,Carroll St & Columbia St,40.683046,-74.003486,4B95A2921AD1EDB7,casual,2022,New York City

In [20]:
df1.to_csv ('Resources/citibike_2017_to_2022.csv', index = False, header=True)

In [21]:
df1["start_station_name"].value_counts()

W 21 St & 6 Ave                      49198
E 17 St & Broadway                   42918
Broadway & E 14 St                   37711
6 Ave & W 33 St                      37410
8 Ave & W 31 St                      36348
University Pl & E 14 St              35977
1 Ave & E 68 St                      35835
Broadway & W 25 St                   34544
West St & Chambers St                34056
Lafayette St & E 8 St                33654
8 Ave & W 33 St                      33450
W 41 St & 8 Ave                      32768
W 31 St & 7 Ave                      31944
9 Ave & W 22 St                      29959
Central Park S & 6 Ave               29533
1 Ave & E 16 St                      29533
Pershing Square North                29507
Cleveland Pl & Spring St             29202
Grand St & Elizabeth St              29100
Broadway & W 58 St                   28149
Broadway & W 29 St                   27523
E 33 St & 1 Ave                      27352
Broadway & W 41 St                   27303
W 18 St & 6 Ave                      27259
Christopher St & Greenwich St        27211
W 22 St & 10 Ave                     27053
W 24 St & 7 Ave                      26832
9 Ave & W 45 St                      26268
E 10 St & Avenue A                   26237
1 Ave & E 18 St                      26077
E 13 St & Avenue A                   26072
Columbus Ave & W 72 St               26027
Lafayette St & Jersey St             25708
W 4 St & 7 Ave S                     25628
12 Ave & W 40 St                     25546
Grand Army Plaza & Central Park S    25165
Great Jones St                       25115
Name: start_station_name, dtype: int64

In [22]:
df1["start_lat"].value_counts()

40.741740    47090
40.737050    41446
40.734546    36418
40.749013    35617
40.750585    35008
             ...
40.727634        1
40.717989        1
40.718024        1
40.717446        1
40.776888        1
Name: start_lat, Length: 39284, dtype: int64